blog_about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'AirBlogBundle:Pages:about.html.twig'

air_blog_pages:
    resource: "@AirBlogBundle/Controller/PagesController.php"
    type:     annotation
    prefix:   /

air_blog_posts:
    resource: "@AirBlogBundle/Controller/PostsController.php"
    type:     annotation
    prefix:   /