AppBundle\Entity\Marker:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MarkerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lat:
            type: float
            precision: 10
            scale: 6
        lng:
            type: float
            precision: 10
            scale: 6
        name:
            type: string
            length: '200'
    lifecycleCallbacks: {  }
